/**
 * Brings rendered sprites into the game.
 *
 * tools/render-sprites.py renders every model in a kit, at every yaw, into a
 * scratch directory; this picks the ones the game actually uses, copies them
 * into assets/props3d/ under the names the game knows them by, and writes the
 * size table beside them.
 *
 * The table is generated rather than kept by hand because it was kept by hand
 * once: eight models' worth of widths and depths transcribed into assets.ts, and
 * a ninth that was baked, sized and used but never added to the loader, which
 * then drew nothing at all for several days without ever failing.
 *
 *     node tools/import-models.mjs <render dir>
 */

import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * What the game calls each model, and how many turns of it to carry.
 *
 * Eight yaws for anything with a front; one for anything round, because a
 * cylinder under a fixed sun looks the same however it is turned and eight
 * copies of it would be eight copies of the same file.
 */
const KIT = [
  // The buildings a works yard is made of.
  { name: 'works', from: 'building-l', yaws: 8 },
  { name: 'factory', from: 'building-e', yaws: 8 },
  { name: 'shed', from: 'building-r', yaws: 8 },
  { name: 'hall', from: 'building-q', yaws: 8 },
  { name: 'depot', from: 'building-s', yaws: 8 },
  { name: 'plant', from: 'building-c', yaws: 8 },
  // Round things, and small things that fill the ground between the buildings.
  { name: 'tank', from: 'detail-tank-large', yaws: 1 },
  { name: 'tank-small', from: 'detail-tank', yaws: 4 },
  { name: 'chimney', from: 'chimney-large', yaws: 1 },
  { name: 'water-tower', from: 'water-tower', yaws: 1 },
  { name: 'container', from: 'shipping-container-a', yaws: 4 },
  { name: 'container-b', from: 'shipping-container-b', yaws: 4 },
  { name: 'container-c', from: 'shipping-container-c', yaws: 4 },
  { name: 'solar', from: 'solar-panel-landscape-group', yaws: 4 }
];

const source = process.argv[2];
if (!source) {
  console.error('usage: node tools/import-models.mjs <render dir>');
  process.exit(1);
}

const rendered = JSON.parse(readFileSync(join(source, 'manifest.json'), 'utf8'));
const byName = new Map(rendered.map((entry) => [entry.name, entry]));

const out = 'assets/props3d';
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

const entries = [];
let bytes = 0;

for (const item of KIT) {
  const info = byName.get(item.from);
  if (!info) throw new Error(`${item.from} was not rendered`);
  const available = info.yaws ?? 1;
  if (item.yaws > available) throw new Error(`${item.from} has ${available} yaws, wanted ${item.yaws}`);

  // Taking four yaws out of eight means every second one.
  const stride = available / item.yaws;
  for (let k = 0; k < item.yaws; k++) {
    const step = Math.round(k * stride);
    const from = available === 1 ? `${item.from}.png` : `${item.from}-${step}.png`;
    const to = item.yaws === 1 ? `${item.name}.png` : `${item.name}-${k}.png`;
    copyFileSync(join(source, from), join(out, to));
    bytes += statSync(join(out, to)).size;
  }

  const spans = [];
  const anchors = [];
  for (let k = 0; k < item.yaws; k++) {
    const step = Math.round(k * stride);
    spans.push(info.spans[step]);
    anchors.push(info.anchors[step]);
  }

  entries.push({
    name: item.name,
    yaws: item.yaws,
    width: info.width,
    depth: info.depth,
    height: info.height,
    spans,
    anchors
  });
}

const body = entries
  .map((e) => `  '${e.name}': { yaws: ${e.yaws}, width: ${e.width}, depth: ${e.depth},` +
    ` height: ${e.height},\n    spans: [${e.spans.join(', ')}],` +
    `\n    anchors: [${e.anchors.join(', ')}] }`)
  .join(',\n');

writeFileSync('src/models.generated.ts', `/**
 * Generated by tools/import-models.mjs — do not edit.
 *
 * Every number here was measured off the model in Blender, not chosen: width,
 * depth and height are the true bounding box in kit units; \`spans\` is what each
 * turn of the model was framed across, so the game can scale a sprite by what it
 * holds rather than by an assumption; and \`anchors\` is how far the footprint
 * sits below the middle of each image once the camera is tilted.
 */

export interface ModelInfo {
  /** How many turns of this model exist, as <name>-0 … <name>-(n-1). */
  yaws: number;
  width: number;
  depth: number;
  height: number;
  /** What each turn was framed across, in model units. */
  spans: number[];
  /** How far below the middle of each sprite its footprint sits, as a fraction. */
  anchors: number[];
}

export const MODELS: Record<string, ModelInfo> = {
${body}
};

export const MODEL_NAMES = Object.keys(MODELS);
`);

console.log(`${entries.length} models, ${entries.reduce((s, e) => s + e.yaws, 0)} sprites, ${(bytes / 1024).toFixed(0)}KB`);
