/**
 * Generated by tools/import-models.mjs — do not edit.
 *
 * Every number here was measured off the model in Blender, not chosen: width,
 * depth and height are the true bounding box in kit units; `spans` is what each
 * turn of the model was framed across, so the game can scale a sprite by what it
 * holds rather than by an assumption; and `anchors` is how far the footprint
 * sits below the middle of each image once the camera is tilted.
 */

export interface ModelInfo {
  /** How many turns of this model exist, as <name>-0 … <name>-(n-1). */
  yaws: number;
  width: number;
  depth: number;
  height: number;
  /** What each turn was framed across, in model units. */
  spans: number[];
  /** How far below the middle of each sprite its footprint sits, as a fraction. */
  anchors: number[];
}

export const MODELS: Record<string, ModelInfo> = {
  'works': { yaws: 8, width: 2.084, depth: 1.87, height: 1.925,
    spans: [2.7004, 3.6445, 2.9183, 3.6445, 2.7004, 3.6445, 2.9183, 3.6445],
    anchors: [0.1335, 0.0989, 0.1236, 0.0989, 0.1335, 0.0989, 0.1236, 0.0989] },
  'factory': { yaws: 8, width: 1.684, depth: 1.29, height: 1.65,
    spans: [1.9956, 2.8244, 2.397, 2.8244, 1.9956, 2.8244, 2.397, 2.8244],
    anchors: [0.1549, 0.1094, 0.1289, 0.1094, 0.1549, 0.1094, 0.1289, 0.1094] },
  'shed': { yaws: 8, width: 2.484, depth: 1.272, height: 1.393,
    spans: [2.7319, 3.2825, 3.107, 3.2825, 2.7319, 3.2825, 3.107, 3.2825],
    anchors: [0.0955, 0.0795, 0.084, 0.0795, 0.0955, 0.0795, 0.084, 0.0795] },
  'hall': { yaws: 8, width: 2.14, depth: 1.77, height: 0.88,
    spans: [2.354, 3.1824, 2.5452, 3.1824, 2.354, 3.1824, 2.5452, 3.1824],
    anchors: [0.07, 0.0518, 0.0648, 0.0518, 0.07, 0.0518, 0.0648, 0.0518] },
  'depot': { yaws: 8, width: 2.12, depth: 0.916, height: 0.837,
    spans: [2.332, 2.5345, 2.507, 2.5345, 2.332, 2.5345, 2.507, 2.5345],
    anchors: [0.0672, 0.0618, 0.0625, 0.0618, 0.0672, 0.0618, 0.0625, 0.0618] },
  'plant': { yaws: 8, width: 1.876, depth: 2.108, height: 1.25,
    spans: [2.6651, 3.3882, 2.4284, 3.3882, 2.6651, 3.3882, 2.4284, 3.3882],
    anchors: [0.0879, 0.0691, 0.0964, 0.0691, 0.0879, 0.0691, 0.0964, 0.0691] },
  'tank': { yaws: 1, width: 1.508, depth: 1.648, height: 0.962,
    spans: [2.0775],
    anchors: [0.0867] },
  'tank-small': { yaws: 4, width: 0.848, depth: 0.515, height: 0.415,
    spans: [0.9328, 1.036, 0.9328, 1.036],
    anchors: [0.0834, 0.0751, 0.0834, 0.0751] },
  'chimney': { yaws: 1, width: 1.08, depth: 1.08, height: 1.7,
    spans: [1.802],
    anchors: [0.1767] },
  'water-tower': { yaws: 1, width: 0.852, depth: 0.832, height: 2.142,
    spans: [1.7309],
    anchors: [0.2318] },
  'container': { yaws: 4, width: 0.373, depth: 0.823, height: 0.348,
    spans: [0.9824, 0.9049, 0.9824, 0.9049],
    anchors: [0.0664, 0.0721, 0.0664, 0.0721] },
  'container-b': { yaws: 4, width: 0.373, depth: 0.823, height: 0.348,
    spans: [0.9824, 0.9049, 0.9824, 0.9049],
    anchors: [0.0664, 0.0721, 0.0664, 0.0721] },
  'container-c': { yaws: 4, width: 0.373, depth: 0.823, height: 0.348,
    spans: [0.9824, 0.9049, 0.9824, 0.9049],
    anchors: [0.0664, 0.0721, 0.0664, 0.0721] },
  'solar': { yaws: 4, width: 1.513, depth: 0.895, height: 0.262,
    spans: [1.6647, 1.6516, 1.6647, 1.6516],
    anchors: [0.0295, 0.0298, 0.0295, 0.0298] }
};

export const MODEL_NAMES = Object.keys(MODELS);
